repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - { id: check-added-large-files, args: ["--maxkb=15000"] }
      - { id: check-case-conflict }
      - { id: detect-private-key }
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.10
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix , --exit-non-zero-on-fix ]
      # Run the formatter.
      - id: ruff-format